server:
  port: :4000
  version: 1.0
  jwtSecret: 38324

mysql:
  driverName: mysql
  host: 127.0.0.1
  port: 3307   # docker 端口3307:3306
  database: grpc_todolist
  username: root
  password: root
  charset: utf8mb4

redis:
  user_name: default
  address: 127.0.0.1:6380 # docker 6380:6379
  password:

etcd:
  address: 127.0.0.1:2379

services:
  gateway:
    name: gateway
    loadBalance: true
    addr:
      - 127.0.0.1:10001
  user:
    name: user
    loadBalance: false
    addr:
      - 127.0.0.1:10002
      - 127.0.0.1:10004   # 多节点，实现负载均衡，防止多节点故障
      - 127.0.0.1:10005
  task:
    name: task
    loadBalance: false
    addr:
      - 127.0.0.1:10003
  lottery:
    name: lottery
    loadBalance: false
    addr:
      - 127.0.0.1:10008
      - 127.0.0.1:10009
      - 127.0.0.1:10010

domain:
  user:
    name: user
  task:
    name: task
  lottery:
    name: lottery